[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "snag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
]

[tool.setuptools.package-dir]
snag = "snag"

[dependency-groups]
dev = [
    "ruff>=0.15.22",
]
